// Keeps the production PostgreSQL schema in step with the SQLite source schema (02-design.md §Deployment).
//
//   node scripts/postgres-schema.mjs migration <name>   regenerate prisma/postgres/schema.prisma and write its migration
//   node scripts/postgres-schema.mjs check              exit 1 when the generated schema is out of date
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const backendDir = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = join(backendDir, 'prisma', 'schema.prisma');
const postgresDir = join(backendDir, 'prisma', 'postgres');
const postgresPath = join(postgresDir, 'schema.prisma');
const migrationsDir = join(postgresDir, 'migrations');

const sqliteDatasource = /datasource db \{\s*provider\s*=\s*"sqlite"\s*url\s*=\s*env\("DATABASE_URL"\)\s*\}/;
const postgresDatasource = `datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  // Migrations use a direct (unpooled) connection.
  directUrl = env("DIRECT_URL")
}`;

/** The PostgreSQL version of the SQLite schema: only the datasource differs. */
export function toPostgresSchema(sqliteSchema) {
  const text = sqliteSchema.replace(/\r\n/g, '\n');
  if (!sqliteDatasource.test(text)) throw new Error('schema.prisma no longer has the expected SQLite datasource block.');
  return `// GENERATED from ../schema.prisma by scripts/postgres-schema.mjs. Do not edit; change ../schema.prisma instead.\n${text.replace(sqliteDatasource, postgresDatasource)}`;
}

export function expectedPostgresSchema() {
  return toPostgresSchema(readFileSync(sourcePath, 'utf8'));
}

// Run the Prisma CLI with this Node directly: no shell, so paths need no quoting on any platform.
const prismaCli = createRequire(import.meta.url).resolve('prisma/build/index.js');
function prisma(args) {
  return execFileSync(process.execPath, [prismaCli, ...args], { cwd: backendDir, encoding: 'utf8' });
}

function writeMigration(name) {
  if (!/^[a-z0-9_]+$/.test(name)) throw new Error('Name the migration with lowercase letters, digits and underscores, e.g. add_site_settings.');
  const next = expectedPostgresSchema();
  const nextPath = join(postgresDir, '.next.prisma');
  mkdirSync(migrationsDir, { recursive: true });
  writeFileSync(nextPath, next);
  try {
    const from = existsSync(postgresPath) ? ['--from-schema-datamodel', postgresPath] : ['--from-empty'];
    const sql = prisma(['migrate', 'diff', ...from, '--to-schema-datamodel', nextPath, '--script']);
    if (/^-- This is an empty migration\.\s*$/.test(sql.trim())) {
      console.log('The PostgreSQL schema is already up to date; no migration written.');
    } else {
      const stamp = new Date().toISOString().replace(/\D/g, '').slice(0, 14);
      const dir = join(migrationsDir, `${stamp}_${name}`);
      mkdirSync(dir, { recursive: true });
      writeFileSync(join(dir, 'migration.sql'), sql);
      console.log(`Wrote ${dir}`);
    }
    writeFileSync(join(migrationsDir, 'migration_lock.toml'), '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n');
    writeFileSync(postgresPath, next);
  } finally {
    rmSync(nextPath, { force: true });
  }
}

const [command, name] = process.argv.slice(2);
if (command === 'migration') {
  writeMigration(name ?? '');
} else if (command === 'check') {
  const current = existsSync(postgresPath) ? readFileSync(postgresPath, 'utf8') : '';
  if (current !== expectedPostgresSchema()) {
    console.error('prisma/postgres/schema.prisma is out of date. Run: npm run postgres:migration --workspace backend -- <name>');
    process.exit(1);
  }
  console.log('The PostgreSQL schema is up to date.');
} else if (command) {
  console.error(`Unknown command "${command}". Use "migration <name>" or "check".`);
  process.exit(1);
}
